import type { NodeOffer, WorkloadKind, WorkloadPreset } from "./domain";

const creatorCatalog: readonly WorkloadKind[] = ["generative-video", "image-batch", "fine-tune", "blender-render"];
const fullCatalog: readonly WorkloadKind[] = [...creatorCatalog, "simulation"];
const computeCatalog: readonly WorkloadKind[] = ["image-batch", "fine-tune", "simulation"];

export const nodeOffers: NodeOffer[] = [
  {
    id: "n-mum-4090-01",
    alias: "monsoon-01",
    gpu: "RTX 4090",
    vramGb: 24,
    region: "ap-south",
    city: "Mumbai",
    pricePerHour: 0.43,
    reliability: 99.1,
    latencyMs: 18,
    carbonGramsPerKwh: 418,
    trustScore: 96,
    benchmarkScore: 91,
    queueSeconds: 4,
    status: "ready",
    evidenceTier: "isolated",
    secureBoot: true,
    supportedWorkloads: creatorCatalog,
    coordinates: { x: 68, y: 58 },
  },
  {
    id: "n-blr-5090-02",
    alias: "indigo-02",
    gpu: "RTX 5090",
    vramGb: 32,
    region: "ap-south",
    city: "Bengaluru",
    pricePerHour: 0.71,
    reliability: 98.7,
    latencyMs: 24,
    carbonGramsPerKwh: 372,
    trustScore: 94,
    benchmarkScore: 100,
    queueSeconds: 8,
    status: "ready",
    evidenceTier: "isolated",
    secureBoot: true,
    supportedWorkloads: fullCatalog,
    coordinates: { x: 70, y: 67 },
  },
  {
    id: "n-sgp-l40s-03",
    alias: "orchid-03",
    gpu: "L40S",
    vramGb: 48,
    region: "ap-southeast",
    city: "Singapore",
    pricePerHour: 1.06,
    reliability: 99.7,
    latencyMs: 41,
    carbonGramsPerKwh: 364,
    trustScore: 99,
    benchmarkScore: 96,
    queueSeconds: 2,
    status: "ready",
    evidenceTier: "isolated",
    secureBoot: true,
    supportedWorkloads: fullCatalog,
    coordinates: { x: 81, y: 69 },
  },
  {
    id: "n-fra-a6000-04",
    alias: "rhine-04",
    gpu: "RTX A6000",
    vramGb: 48,
    region: "eu-central",
    city: "Frankfurt",
    pricePerHour: 0.82,
    reliability: 97.8,
    latencyMs: 112,
    carbonGramsPerKwh: 338,
    trustScore: 91,
    benchmarkScore: 84,
    queueSeconds: 12,
    status: "ready",
    evidenceTier: "observed",
    secureBoot: false,
    supportedWorkloads: creatorCatalog,
    coordinates: { x: 51, y: 39 },
  },
  {
    id: "n-hel-4090-05",
    alias: "aurora-05",
    gpu: "RTX 4090",
    vramGb: 24,
    region: "eu-central",
    city: "Helsinki",
    pricePerHour: 0.49,
    reliability: 99.4,
    latencyMs: 128,
    carbonGramsPerKwh: 82,
    trustScore: 98,
    benchmarkScore: 90,
    queueSeconds: 6,
    status: "ready",
    evidenceTier: "isolated",
    secureBoot: true,
    supportedWorkloads: creatorCatalog,
    coordinates: { x: 53, y: 25 },
  },
  {
    id: "n-par-a100-06",
    alias: "atelier-06",
    gpu: "A100 80GB",
    vramGb: 80,
    region: "eu-west",
    city: "Paris",
    pricePerHour: 1.54,
    reliability: 99.9,
    latencyMs: 119,
    carbonGramsPerKwh: 69,
    trustScore: 100,
    benchmarkScore: 100,
    queueSeconds: 18,
    status: "busy",
    evidenceTier: "isolated",
    secureBoot: true,
    supportedWorkloads: computeCatalog,
    coordinates: { x: 47, y: 42 },
  },
  {
    id: "n-iad-4090-07",
    alias: "capitol-07",
    gpu: "RTX 4090",
    vramGb: 24,
    region: "us-east",
    city: "Ashburn",
    pricePerHour: 0.38,
    reliability: 96.9,
    latencyMs: 182,
    carbonGramsPerKwh: 334,
    trustScore: 88,
    benchmarkScore: 89,
    queueSeconds: 3,
    status: "ready",
    evidenceTier: "observed",
    secureBoot: false,
    supportedWorkloads: creatorCatalog,
    coordinates: { x: 25, y: 43 },
  },
  {
    id: "n-yul-5090-08",
    alias: "maple-08",
    gpu: "RTX 5090",
    vramGb: 32,
    region: "us-east",
    city: "Montréal",
    pricePerHour: 0.64,
    reliability: 99.3,
    latencyMs: 171,
    carbonGramsPerKwh: 32,
    trustScore: 97,
    benchmarkScore: 99,
    queueSeconds: 9,
    status: "ready",
    evidenceTier: "isolated",
    secureBoot: true,
    supportedWorkloads: fullCatalog,
    coordinates: { x: 23, y: 32 },
  },
  {
    id: "n-pdx-l40s-09",
    alias: "cascade-09",
    gpu: "L40S",
    vramGb: 48,
    region: "us-west",
    city: "Portland",
    pricePerHour: 0.97,
    reliability: 98.9,
    latencyMs: 211,
    carbonGramsPerKwh: 91,
    trustScore: 95,
    benchmarkScore: 95,
    queueSeconds: 5,
    status: "ready",
    evidenceTier: "isolated",
    secureBoot: true,
    supportedWorkloads: fullCatalog,
    coordinates: { x: 10, y: 38 },
  },
  {
    id: "n-sfo-h100-10",
    alias: "sequoia-10",
    gpu: "H100 80GB",
    vramGb: 80,
    region: "us-west",
    city: "San Jose",
    pricePerHour: 2.34,
    reliability: 99.8,
    latencyMs: 224,
    carbonGramsPerKwh: 176,
    trustScore: 99,
    benchmarkScore: 100,
    queueSeconds: 24,
    status: "draining",
    evidenceTier: "attested",
    secureBoot: true,
    supportedWorkloads: computeCatalog,
    coordinates: { x: 9, y: 52 },
  },
];

export const workloadPresets: WorkloadPreset[] = [
  {
    id: "generative-video",
    label: "Launch film / 480 frames",
    summary: "Checkpointed diffusion-video render with frame-level output validation.",
    minVramGb: 24,
    gpuCount: 3,
    durationMinutes: 96,
    maxPricePerGpuHour: 1.2,
  },
  {
    id: "fine-tune",
    label: "LoRA fine-tune / 12k steps",
    summary: "Resumable training scenario with metric-checkpoint and deterministic-sample policies.",
    minVramGb: 32,
    gpuCount: 2,
    durationMinutes: 180,
    maxPricePerGpuHour: 1.8,
  },
  {
    id: "image-batch",
    label: "Campaign set / 1,000 images",
    summary: "Parallel image generation with content and resolution policy checks.",
    minVramGb: 16,
    gpuCount: 4,
    durationMinutes: 72,
    maxPricePerGpuHour: 0.9,
  },
  {
    id: "blender-render",
    label: "Blender sequence / 2,400 frames",
    summary: "Frame sharding, checksum validation, and failed-frame replay.",
    minVramGb: 16,
    gpuCount: 4,
    durationMinutes: 210,
    maxPricePerGpuHour: 0.8,
  },
  {
    id: "simulation",
    label: "Monte Carlo / 50M paths",
    summary: "Deterministic shard seeds with replicated sample verification.",
    minVramGb: 24,
    gpuCount: 3,
    durationMinutes: 55,
    maxPricePerGpuHour: 1.1,
  },
];

export const defaultPriorities = {
  cost: 0.28,
  reliability: 0.27,
  carbon: 0.16,
  latency: 0.09,
  trust: 0.2,
} as const;
